name: test
on: [pull_request, workflow_dispatch]

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
      - name: Run tests
        run: ./src/test

  rust-bindings:
    runs-on: ubuntu-latest
    name: (${{ matrix.target }})
    strategy:
      matrix:
        target: [
          x86_64-unknown-linux-gnu,
          aarch64-unknown-linux-gnu,
        ]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}
    - name: Build and Test
      run: |
        cd rust_bindings 
        cargo build --release
        cargo test

  nim:
    name: nim
    runs-on: ubuntu-latest
    steps:
      - uses: jiro4989/setup-nim-action@v1
      - uses: actions/checkout@v3
      - name: Run Nim test
        run: nim c -r tests/test_hashtree_abi.nim
